export const countryCurrencies = [
    { "United States": "USD" },
    { "United Arab Emirates": "AED" },
    { "Afghanistan": "AFN" },
    { "Albania": "ALL" },
    { "Armenia": "AMD" },
    { "Netherlands Antilles": "ANG" },
    { "Angola": "AOA" },
    { "Argentina": "ARS" },
    { "Australia": "AUD" },
    { "Aruba": "AWG" },
    { "Azerbaijan": "AZN" },
    { "Bosnia and Herzegovina": "BAM" },
    { "Barbados": "BBD" },
    { "Bangladesh": "BDT" },
    { "Bulgaria": "BGN" },
    { "Bahrain": "BHD" },
    { "Burundi": "BIF" },
    { "Bermuda": "BMD" },
    { "Brunei": "BND" },
    { "Bolivia": "BOB" },
    { "Brazil": "BRL" },
    { "Bahamas": "BSD" },
    { "Bhutan": "BTN" },
    { "Botswana": "BWP" },
    { "Belarus": "BYN" },
    { "Belize": "BZD" },
    { "Canada": "CAD" },
    { "Democratic Republic of the Congo": "CDF" },
    { "Switzerland": "CHF" },
    { "Chile": "CLP" },
    { "China": "CNY" },
    { "Colombia": "COP" },
    { "Costa Rica": "CRC" },
    { "Cuba": "CUC" },
    { "Cape Verde": "CVE" },
    { "Czech Republic": "CZK" },
    { "Djibouti": "DJF" },
    { "Denmark": "DKK" },
    { "Dominican Republic": "DOP" },
    { "Algeria": "DZD" },
    { "Egypt": "EGP" },
    { "Eritrea": "ERN" },
    { "Ethiopia": "ETB" },
    { "European Union": "EUR" },
    { "Fiji": "FJD" },
    { "Falkland Islands": "FKP" },
    { "United Kingdom": "GBP" },
    { "Georgia": "GEL" },
    { "Ghana": "GHS" },
    { "Gibraltar": "GIP" },
    { "Gambia": "GMD" },
    { "Guinea": "GNF" },
    { "Guatemala": "GTQ" },
    { "Guyana": "GYD" },
    { "Hong Kong": "HKD" },
    { "Honduras": "HNL" },
    { "Croatia": "HRK" },
    { "Haiti": "HTG" },
    { "Hungary": "HUF" },
    { "Indonesia": "IDR" },
    { "Israel": "ILS" },
    { "India": "INR" },
    { "Iraq": "IQD" },
    { "Iran": "IRR" },
    { "Iceland": "ISK" },
    { "Jamaica": "JMD" },
    { "Jordan": "JOD" },
    { "Japan": "JPY" },
    { "Kenya": "KES" },
    { "Kyrgyzstan": "KGS" },
    { "Cambodia": "KHR" },
    { "Comoros": "KMF" },
    { "North Korea": "KPW" },
    { "South Korea": "KRW" },
    { "Kuwait": "KWD" },
    { "Cayman Islands": "KYD" },
    { "Kazakhstan": "KZT" },
    { "Laos": "LAK" },
    { "Lebanon": "LBP" },
    { "Sri Lanka": "LKR" },
    { "Liberia": "LRD" },
    { "Lesotho": "LSL" },
    { "Libya": "LYD" },
    { "Morocco": "MAD" },
    { "Moldova": "MDL" },
    { "Madagascar": "MGA" },
    { "North Macedonia": "MKD" },
    { "Myanmar": "MMK" },
    { "Mongolia": "MNT" },
    { "Macau": "MOP" },
    { "Mauritania": "MRO" },
    { "Mauritius": "MUR" },
    { "Maldives": "MVR" },
    { "Malawi": "MWK" },
    { "Mexico": "MXN" },
    { "Malaysia": "MYR" },
    { "Mozambique": "MZN" },
    { "Namibia": "NAD" },
    { "Nigeria": "NGN" },
    { "Nicaragua": "NIO" },
    { "Norway": "NOK" },
    { "Nepal": "NPR" },
    { "New Zealand": "NZD" },
    { "Oman": "OMR" },
    { "Panama": "PAB" },
    { "Peru": "PEN" },
    { "Papua New Guinea": "PGK" },
    { "Philippines": "PHP" },
    { "Pakistan": "PKR" },
    { "Poland": "PLN" },
    { "Paraguay": "PYG" },
    { "Qatar": "QAR" },
    { "Romania": "RON" },
    { "Serbia": "RSD" },
    { "Russia": "RUB" },
    { "Rwanda": "RWF" },
    { "Saudi Arabia": "SAR" },
    { "Solomon Islands": "SBD" },
    { "Seychelles": "SCR" },
    { "Sudan": "SDG" },
    { "Sweden": "SEK" },
    { "Singapore": "SGD" },
    { "Saint Helena": "SHP" },
    { "Sierra Leone": "SLL" },
    { "Somalia": "SOS" },
    { "Suriname": "SRD" },
    { "South Sudan": "SSP" },
    { "Sao Tome and Principe": "STN" },
    { "El Salvador": "SVC" },
    { "Syria": "SYP" },
    { "Swaziland": "SZL" },
    { "Thailand": "THB" },
    { "Tajikistan": "TJS" },
    { "Turkmenistan": "TMT" },
    { "Tunisia": "TND" },
    { "Tonga": "TOP" },
    { "Turkey": "TRY" },
    { "Trinidad and Tobago": "TTD" },
    { "Taiwan": "TWD" },
    { "Tanzania": "TZS" },
    { "Ukraine": "UAH" },
    { "Uganda": "UGX" },
    { "United States": "USD" },
    { "Uruguay": "UYU" },
    { "Uzbekistan": "UZS" },
    { "Venezuela": "VEF" },
    { "Vietnam": "VND" },
    { "Vanuatu": "VUV" },
    { "Samoa": "WST" },
    { "Central African CFA Franc": "XAF" },
    { "East Caribbean Dollar": "XCD" },
    { "West African CFA Franc": "XOF" },
    { "CFP Franc": "XPF" },
    { "Yemen": "YER" },
    { "South Africa": "ZAR" },
    { "Zambia": "ZMW" },
    { "Zimbabwe": "ZWL" }
];
